version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: todolist-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports: ${DB_PORT}:5432
    volumes: todolist-db-data:/var/lib/postgresql/data

volumes:
  todolist-db-data:
